apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base

namespace: devguardian

commonLabels:
  app.kubernetes.io/name: devguardian
  app.kubernetes.io/component: backend

patchesStrategicMerge:
- overlays/production/
